export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const SET_ANSWER = 'SET_ANSWER'
export const NEXT_QUSTION = 'NEXT_QUSTION'
export const IS_FINISHED = 'IS_FINISHED'
export const RETRY_QUIZ = 'RETRY_QUIZ'

export const ADD_QUESTION = 'ADD_QUESTION'
export const RESET_CREATE_QUIZ = 'RESET_CREATE_QUIZ'